services:
  - type: web
    name: arith-backend
    env: node
    plan: free
    branch: main
    repo: https://github.com/Arithmathsolver/Arith/tree/main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: production
